train: null
inference:
  spectrogram:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.spec_augs.FrequencyMasking
        freq_mask_param: 30
      - _target_: src.transforms.spec_augs.TimeMasking
        p: 1
        time_mask_param: 30
